### ISSUE TITLE
Panic in multicluster-cp pod

### ISSUE THREAD

**Issue by tamalsaha** [open-cluster-management-io/multicluster-controlplane#117]
```
I0829 06:27:13.355606       1 crds.go:80] ocm crd(managedclusteraddons.addon.open-cluster-management.io) is ready
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2349ace]

goroutine 3391 [running]:
github.com/openshift/library-go/pkg/operator/resource/resourceapply.reportCreateEvent({0x0, 0x0}, {0x41b8050, 0xc003470500}, {0x0, 0x0})
	/go/src/open-cluster-management.io/multicluster-controlplane/vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go:28 +0x2ee
github.com/openshift/library-go/pkg/operator/resource/resourceapply.ApplyCustomResourceDefinitionV1({0x41dbac0, 0xc00073ac80}, {0x7fedb0377b38, 0xc004c51140}, {0x0, 0x0}, 0xc003470500)
	/go/src/open-cluster-management.io/multicluster-controlplane/vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/apiextensions.go:22 +0x4f2
open-cluster-management.io/multicluster-controlplane/pkg/agent.(*AgentOptions).ensureCRDs(0xc0065fd680, {0x41dbac0, 0xc00073ac80}, {0x41d66a0, 0xc0076b8930})
	/go/src/open-cluster-management.io/multicluster-controlplane/pkg/agent/agent.go:164 +0x1f0
open-cluster-management.io/multicluster-controlplane/pkg/agent.(*AgentOptions).RunAgent(0xc0065fd680, {0x41dbac0, 0xc00073ac80})
	/go/src/open-cluster-management.io/multicluster-controlplane/pkg/agent/agent.go:133 +0x150
open-cluster-management.io/multicluster-controlplane/pkg/controllers/ocmcontroller.EnableSelfManagement({0x41dbac0, 0xc00073ac80}, 0xc00439e180?, {0x3a85f91, 0x5}, {0xc001a369c0, 0x24})
	/go/src/open-cluster-management.io/multicluster-controlplane/pkg/controllers/ocmcontroller/ocmagent.go:93 +0x6ca
created by open-cluster-management.io/multicluster-controlplane/pkg/controllers/ocmcontroller.InstallSelfManagementCluster.func1
	/go/src/open-cluster-management.io/multicluster-controlplane/pkg/controllers/ocmcontroller/ocmagent.go:55 +0x1e5
```

**Comment by clyang82** [comment]
It was fixed. @tamalsaha Can you help to verify and close it? Thanks.
